plugins {
    id 'org.springframework.boot' version '4.0.2'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'

    // Dependency Updater
    id 'com.github.ben-manes.versions' version '0.53.0'

    // IDEs
    id 'idea'
}

wrapper {
    gradleVersion = 'latest'
    distributionType = Wrapper.DistributionType.BIN
}
