import type { Config } from "tailwindcss";

/**
 * Design tokens mapped from design-reference/scholastic_paper/DESIGN.md.
 * Where the DESIGN.md front-matter and its prose disagree (primary, surface,
 * outline-variant) the prose values — which the screens actually render with —
 * win: primary #2F5D45, canvas #F3F1EC, hairline #E5E0D8.
 */
const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // canvas & paper
        background: "#F3F1EC",
        surface: "#F3F1EC",
        "surface-paper": "#F3F1EC",
        "surface-dim": "#dcdad5",
        "surface-bright": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container": "#f0eee9",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "surface-tint": "#39684f",
        "on-background": "#1b1c19",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#414943",
        "inverse-surface": "#30312e",
        "inverse-on-surface": "#f3f1ec",
        // lines
        outline: "#717972",
        "outline-variant": "#E5E0D8",
        "border-warm": "#E5E0D8",
        "border-warm-strong": "#D8D2C7",
        // brand
        primary: "#2F5D45",
        "primary-dark": "#1E3F2E",
        "on-primary": "#ffffff",
        "primary-container": "#2f5d45",
        "on-primary-container": "#a2d4b6",
        "inverse-primary": "#a0d2b3",
        "primary-fixed": "#bbeecf",
        "primary-fixed-dim": "#a0d2b3",
        "on-primary-fixed": "#002112",
        "on-primary-fixed-variant": "#214f38",
        secondary: "#446652",
        "on-secondary": "#ffffff",
        "secondary-container": "#c3e9d0",
        "on-secondary-container": "#486a56",
        "secondary-fixed": "#c6ebd3",
        "secondary-fixed-dim": "#aacfb8",
        "on-secondary-fixed": "#002112",
        "on-secondary-fixed-variant": "#2c4d3c",
        tertiary: "#363f3b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4d5652",
        "on-tertiary-container": "#c1cbc5",
        "tertiary-fixed": "#dbe5df",
        "tertiary-fixed-dim": "#bfc9c3",
        "on-tertiary-fixed": "#151d1a",
        "on-tertiary-fixed-variant": "#3f4945",
        // semantic
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "tint-green": "#E4EEE8",
        "amber-ink": "#C27D23",
        "amber-wash": "#FDF4E7",
        "terracotta": "#B83A30",
        "blush": "#FBEAE8",
        "ink-muted": "#5C6460",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      // The whole UI renders at 90% (see `html { zoom }` in globals.css), so viewport-height units must be scaled back up.
      height: { screen: "calc(100vh / 0.9)" },
      minHeight: { screen: "calc(100vh / 0.9)" },
      spacing: {
        gutter: "1.5rem",
        "gutter-sm": "1rem",
        "gutter-lg": "2rem",
        margin: "2rem",
        "margin-sm": "1rem",
        "margin-lg": "3.5rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        // Literata = editorial voice, DM Sans = interface utility
        "display-lg": ["Literata Variable", "Literata", "serif"],
        "display-lg-mobile": ["Literata Variable", "Literata", "serif"],
        "headline-lg": ["Literata Variable", "Literata", "serif"],
        "headline-lg-mobile": ["Literata Variable", "Literata", "serif"],
        "headline-md": ["Literata Variable", "Literata", "serif"],
        "headline-sm": ["Literata Variable", "Literata", "serif"],
        "title-editorial": ["Literata Variable", "Literata", "serif"],
        "body-lg": ["DM Sans Variable", "DM Sans", "sans-serif"],
        "body-md": ["DM Sans Variable", "DM Sans", "sans-serif"],
        "body-sm": ["DM Sans Variable", "DM Sans", "sans-serif"],
        "label-lg": ["DM Sans Variable", "DM Sans", "sans-serif"],
        "label-md": ["DM Sans Variable", "DM Sans", "sans-serif"],
        "metadata-caps": ["DM Sans Variable", "DM Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.015em", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "title-editorial": ["18px", { lineHeight: "26px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "metadata-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
export default config;
