blank_issues_enabled: false
contact_links:
  - name: Questions & Support
    url: https://github.com/orgs/openshelves-labs/discussions/categories/q-a
    about: To ask questions or request support from maintainers or other users, please use GitHub Discussions.
